### ISSUE TITLE
Reload/refresh local SQLite DB with a new 'refresh button'

### ISSUE THREAD

**Issue by Chinoman10** [invisal/libsql-studio#125]
So I loaded a local SQLite DB into LibSQL Studio, make some changes, committed and saved the file.
Then I ran a program that made changes to it, but they weren't reflected on the browser, so I assume the browser is only showing the loaded file in memory (_which would make sense_).

Can we have a **refresh button** that reloads the file?

When I dragged the file into Studio a second time (to 'refresh'), I lost all my open tabs and sorts, etc. So if we could have a refresh button so these settings remain set, it would be pretty good UX.

**Comment by invisal** [comment]
We can do it. Let me add this during this Sunday :)

**Comment by invisal** [comment]
This has been addressed
https://github.com/invisal/libsql-studio/commit/d72b787610f0774efd676d735b62eeb8581fcc95

I have added the refresh button. It will reload the data.

**Comment by Chinoman10** [comment]
You work fast man 🔥 thank you!

PS: if you ever consider having a Discord server dedicated to LibSQL Studio, hit me up (_preferably before you start wasting time on it, to avoid common pitfalls_). If you are unsure why you'd want it, here's a great short (_although it's talking about game dev. companies, you have small & large dev. companies such as Cloudflare, Astro, Strapi, Bun, Midjourney, etc. using it for non-game related dev. too_). I'll help you out fam :)
