### ISSUE TITLE
v0.3.0 Roadmap

### ISSUE THREAD

**Issue by invisal** [invisal/libsql-studio#19]
# LibSQL Studio v0.3.0 Roadmap

## What should be direction of LibSQL?

There are hundreds of database GUI in the market. It is very hard for LibSQL Studio to go toe to toe with them because:
- Most of the popular GUI in the market has been developed for years. Dbeaver has developed over 10+ years. TablePlus has developed over 7+ years. They are feature rich and it would take years to catch up.
- We are web-based and there are a lot of restrictions. There are a lot of features that would be impossible to be done in the browser and there are certain task that browser is too slow to perform.

Instead we should focus on what web-based allows us to do best:
- LibSQL Studio should focus on lightweight task such as browsing data and editing table.
- LibSQL Studio will focus on allowing people to collaboration.
- LibSQL Studio will help easing the software development by create building block for developer.

We will attack one use-case at the time.

## Headless CMS Use-case

Our first use-case that we want to solve is to turn Turso + LibSQL Studio into a mini-headless CMS. Here is how it works:
- User create Turso database
- User create LibSQL Studio account
- Add Turso credential into LibSQL Studio
- User can add more user to the project
- User can limit access of what each user can edit in database
- In front-end, user can directly connect to Turso database to display data

In order to achieve, we will add the following features:

## Medium-like Editor

We will integrate with EditorJS (https://editorjs.io/). Any TEXT column can launch an full-fletch WYSIWYG editor. The editor should support:
- Typology (Header, Paragraph, List, etc...)
- Image block
- Code block
- Table

![image](https://github.com/invisal/libsql-studio/assets/4539653/b7874055-78ea-4507-a94a-2fc77baf1124)

## Upload Image into Column

Any TEXT column, we can add ability to upload the image and insert the uploaded image link into the column

![image](https://github.com/invisal/libsql-studio/assets/4539653/3b7b0715-9fdf-423f-9342-5b17e669d92e)

## Two type of connections

LibSQL Studio will offer two type of connections:
- **Direct connection**: LibSQL Studio will act as if it just normal database GUI
- **Managed connection**: LibSQL Studio can add extra functionality such as collaboration.

![image](https://github.com/invisal/libsql-studio/assets/4539653/22c919ec-62b2-4a49-bedc-788025e3b6ed)

## Collaboration

If it is **managed connection**, LibSQL Studio allows owner to add more user to create and edit data. In version v0.3.0, we will not focus on permission restriction. We will add more permission in later version

![image](https://github.com/invisal/libsql-studio/assets/4539653/dc9b35d3-6f89-4824-b48c-a56082a82a76)

---
## Self-Host

LibSQL Studio is an open-source project. https://libsqlstudio.com is the hosted version of LibSQL Studio. If you don't like how  https://libsqlstudio.com operate, everyone is free to host it on your own. I will add more guide on how to self-host LibSQL Studio

**Comment by bryanvaz** [comment]
Nice work! Tried to use it yesterday, but I realized it doesn't have the ability to connect to a locally hosted/self-hosted libsql instance. I was able to jerry rig something together by removing the validation for `token` and using the connection string `ws://localhost:8080`. (works because the underlying `ws` client ignores the jwt param if the token is an empty string)

The locally hosted element will be important during development of any frontend and backend of a headless crm as the most reliable way to do E2E and integration testing (as well as hot-reload dev) will be to swap out the Turso connection string for a docker connection string at the test runner level. That way libsql-studio will be the fastest way to inspect the state of the db and debug.

_The easiest way to start a self hosted libsql server is either via the turso cli or via docker. I'd recommend docker for testing as it'll be deterministic_

**Comment by invisal** [comment]
> Nice work! Tried to use it yesterday, but I realized it doesn't have the ability to connect to a locally hosted/self-hosted libsql instance. I was able to jerry rig something together by removing the validation for `token` and using the connection string `ws://localhost:8080`. (works because the underlying `ws` client ignores the jwt param if the token is an empty string)
> 
> The locally hosted element will be important during development of any frontend and backend of a headless crm as the most reliable way to do E2E and integration testing (as well as hot-reload dev) will be to swap out the Turso connection string for a docker connection string at the test runner level. That way libsql-studio will be the fastest way to inspect the state of the db and debug.
> 
> _The easiest way to start a self hosted libsql server is either via the turso cli or via docker. I'd recommend docker for testing as it'll be deterministic_

Thanks for reporting. I will make the token as optional and it should works with local connection.

**Comment by saeedesmaili** [comment]
Is there any documentation on how this can be self-hosted with docker compose?

**Comment by invisal** [comment]
@saeedesmaili 
- We have Dockerfile https://github.com/outerbase/studio/blob/develop/Dockerfile . At the moment, we don't have official docker image, but build from our Dockerfile.
- There are some people using it in docker compose: https://github.com/outerbase/studio-cli/issues/3
