### ISSUE TITLE
Github permissions

### ISSUE THREAD

**Issue by adriangalilea** [invisal/libsql-studio#26]
<img width="546" alt="image" src="https://github.com/invisal/libsql-studio/assets/90320947/0c719389-c001-45b3-a7f4-1435527fcfd7">

Hello when sign-in up it asks for this permissions, not sure if it can be avoided somehow, why does it need those?

**Comment by rin-yato** [comment]
Those are not what we requested, the only permission that we request is to read your email address.

<img width="536" alt="image" src="https://github.com/invisal/libsql-studio/assets/106462074/8797944f-1b39-4c20-9a59-0bdefe7f8fb4">

**Comment by invisal** [comment]
> <img alt="image" width="546" src="https://private-user-images.githubusercontent.com/90320947/313160951-0c719389-c001-45b3-a7f4-1435527fcfd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDA3MjIsIm5iZiI6MTcxMDUwMDQyMiwicGF0aCI6Ii85MDMyMDk0Ny8zMTMxNjA5NTEtMGM3MTkzODktYzAwMS00NWIzLWE3ZjQtMTQzNTUyN2ZjZmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDExMDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNTkzMTY4YTMwZTZjZWFkMzVhODBkMjdlYzJiOThiYTA1YjI5ODhjZDZkYzc4MDRiMmU1NzQ3ZWUzOWE5ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NZED7O7bb90c73hoQcYHITO-tajCe_zPzVbrm3uZorM">
> Hello when sign-in up it asks for this permissions, not sure if it can be avoided somehow, why does it need those?

- First of all, Github login is optional. You are not required to login to use.
- Currently, login to Github provides no additional feature (the additional features will be on next release where you can sync your connection across different device)
- And finally, we only read your email. The "Act on your behalf" is misleading from Github as we have no permission to act anything.
-
