### ISSUE TITLE
Provide instruction if user does not add CORS

### ISSUE THREAD

**Issue by invisal** [invisal/libsql-studio#60]
I would also see if you can specifically detect if a user doesn't launch with the CORS support enabled, as that will also be a common mistake.

I think the HTTP server will return a distinct error in that case.

**Comment by otoolep** [comment]
![CORS](https://github.com/invisal/libsql-studio/assets/536312/f9bee363-698e-4679-a73e-b1813fd549fb)

Pretty sure it does.

**Comment by invisal** [comment]
@otoolep 

While, the console provides CORS error message, it is not possible for Javascript to catch that error. https://stackoverflow.com/a/19325710

Maybe when user fail to connect for some reason, we can provide list of can go wrong including the CORS instruction.
