### ISSUE TITLE
Support for displaying large numbers

### ISSUE THREAD

**Issue by sveltespot** [invisal/libsql-studio#77]
Hey, thanks for this awesome piece of software. I am currently having an issue where large numbers in my id column (int64) are unable to be displayed, which causes the entire column to not getting displayed. I get the following error:

```
RangeError: Received integer which is too large to be safely represented as a JavaScript number
```

Unfortunately, this is a critical bug for our use case because most of our ids are snowflake IDs which are 64bit integers.

**Comment by invisal** [comment]
Thanks. We will explore the possibility to work with bigint, if it is something that we can quickly do it.

**Comment by invisal** [comment]
This is already in production. We now support big number.
