### ISSUE TITLE
Allow Editing String Primary Key

### ISSUE THREAD

**Issue by zicklag** [invisal/libsql-studio#82]
Have a simple table:

```sql
CREATE TABLE kv ( key string primary key, value text );
```

But in the UI, I'm unable to add a row with a custom key in the table through the table editor, I believe because it's the primary key, and it assumes I'm only going to be inserting either `DEFAULT`, `NULL`, a Unix timestamp, or a UUID.

I can double-click the value cell to edit it, but not the key.

![image](https://github.com/invisal/libsql-studio/assets/25393315/e9980058-5195-46c6-8d2a-36c8fc360fef)

**Comment by invisal** [comment]
I am not able to reproduce this as I can double click it normally.


https://github.com/invisal/libsql-studio/assets/4539653/4ee5184e-f3b0-4323-a2b7-5b71d131a11e

What is your browser and OS?

**Comment by invisal** [comment]
@zicklag 

Fixed and deploy. You can refresh to see the fixed.

**Comment by zicklag** [comment]
Awesome! It works, thanks!

![image](https://github.com/invisal/libsql-studio/assets/25393315/29221c7e-5082-4a42-b704-f4bd92c65273)
